### PR TITLE
Bump version: 0.2.0 → 0.3.0

### LINKED ISSUE #24: New release needed
Can you deploy a new version to PyPyi?

### PR DESCRIPTION
**Pull request by dgrant**
Closes #24

### CODE REVIEW

**Comment by dgrant** [comment]
Why isn't this triggering a build?

**Comment by dgrant** [comment]
Integration not set up I guess. Here is the link to the CI build: https://travis-ci.org/jmrivas86/django-json-widget/builds/567069160

**Comment by dgrant** [comment]
@jmrivas86 Can you take a look and see if this is good to merge?

**Comment by imkaka** [comment]
This seems inactive, should anyone fork it and release it PyPI with the latest changes? @dgrant @jmrivas86

**Comment by jmrivas86** [comment]
@imaka @dgrant  The project is not inactive, I have been a father a few months ago and the dedication time is less but I am working on getting a new version with all the issues fixed and some more updates

**Comment by jmrivas86** [comment]
I have good news, I just published the 1.0.0 version, the first Stable version ! 🎉 🐍

**Pull request closed without merging**
