### PR TITLE
Stop declaring support for Django versions before 3.2

### PR DESCRIPTION
**Pull request by ashokdelphia**
(I based the branch on the one for #56, to avoid obvious conflicts; the intended change here is commit 78bfa2e4182e004d8f9937319d89806b1856b35e onwards.)

* Stop declaring support for Django versions before 2.2. (78bfa2e)

    Version 2.1 has been out of extended support by Django since April 2019. Version 2.2 LTS is due to pass out of extended support this coming April. 3.0 and 3.1 passed out of extended support last year, but I've left them alone so that the supported versions still form a contiguous range.
    
    My motivation is to drop support for version 2.1 and earlier is to to facilitate fixing an HTML injection using the 'json_script' template filter; see PR #64. This was introduced in version 2.1, but my hope is that it's reasonable to drop support for versions that have been unsupported by Django for years.
    
    (I see that the version declared in requirements.txt is already excluding 2.1 and earlier; I'm unclear whether the difference is deliberate or not.)

* Drop support for Python 2.7. (886d983)

    Since Django 1.11 LTS was the last to support Python 2.7, if we're no longer supporting Django pre-2.2, then we no longer need to consider Python 2.7.

* Stop using 'future' to enable support for Python 2.7. (b7f92ba)

* Remove the claim of support for Django before version 3.2. (7d56081)

    All of these older versions are now EOL, with 3.2 LTS being the oldest supported version by Django.
    
    I'd like to add a claim of support for current Django version 4 onwards, but I think it makes sense to do that as a separate change to this one, and it deserves some work to ensure that it works as expected and in tests.

* Adjust version constraint to match what's defined for tests. (6130850)

    I'm taking the comment at face value, so assuming this can also be removed.

* Remove note about Django <3.1 from the readme. (ed38a4d)

    The example still uses the postgres-specific version, so will also need to be updated.

### CODE REVIEW

**Comment by ashokdelphia** [comment]
Since Django 1.1 LTS was the last to support Python 2.7, I wonder if it may be worth dropping support for that here, too.

**Comment by StevenMapes** [comment]
Yes it should be and then futures can also be removed

**Review by StevenMapes — APPROVED** [review]
Looks good to me, would be nice to get this project update to remove the old support and add in the new support for 3.2, 4.0, 4.1 and 4.2 when the alpha is released shortly

**Comment by ashokdelphia** [comment]
> Looks good to me, would be nice to get this project update to remove the old support and add in the new support for 3.2, 4.0, 4.1 and 4.2 when the alpha is released shortly

I'll take out pre-3.2 here, too.

When I first opened it, 2.2 wasn't quite out of long-term support.

**Pull request merged**
