### PR TITLE
Remove source map reference from JS bundle

### PR DESCRIPTION
**Pull request by stefanw**
Starting in Django 4 the manifest static file storage will try to post process source map references. The source map is not available in this app which will lead to an error when running manage.py collectstatic. Removing the reference clears the error.

See https://docs.djangoproject.com/en/4.0/ref/contrib/staticfiles/#manifeststaticfilesstorage

### CODE REVIEW

**Review by StevenMapes — APPROVED** [review]
I agree with the change

**Comment by dgorobets** [comment]
Any update on this?

**Comment by StevenMapes** [comment]
I messaged José on Twitter and he's going to look to update the project next month as he's really busy at the moment it seems, so hopefully before the end of June there'll be an updated release on pypi with this update as well as the other three PRs that have come in at the very least :)

**Comment by bmull** [comment]
Can we please merge this?

**Comment by theognis1002** [comment]
Please merge! @StevenMapes

**Comment by StevenMapes** [comment]
> Please merge! @StevenMapes

I do not have permission to perform merges you'll need to contact @jmrivas86

**Comment by StevenMapes** [comment]
@jmrivas86 - could you publish a new version to pypi please

**Comment by ekaj2** [comment]
In the interim, you can use this in your requirements.in:

```bash
# remove the pypi dep
# django-json-widget==1.1.1

# reference this w/ GitHub and pin the commit hash where this was merged
git+https://github.com/jmrivas86/django-json-widget.git@6141d61#egg=django-json-widget
```

**Comment by ekaj2** [comment]
In the interim, you can use this in your requirements.in:

```bash
# remove the pypi dep
# django-json-widget==1.1.1

# reference this w/ GitHub and pin the commit hash where this was merged
git+https://github.com/jmrivas86/django-json-widget.git@6141d61#egg=django-json-widget
```

**Comment by sowinski** [comment]
Please publish a new version :)

**Comment by sowinski** [comment]
> ```shell
> 6141d61
> ```

For me this did not work. Are you sure about the correct commit tag?

**Comment by ekaj2** [comment]
Yup that's what we use, but use any commit/branch you want: https://github.com/jmrivas86/django-json-widget/commits/master/

Format is slightly different depending on your pip tool though, so read the documentation if you don't just use vanilla pip

**Comment by sowinski** [comment]
> Yup that's what we use, but use any commit/branch you want: https://github.com/jmrivas86/django-json-widget/commits/master/
> 
> Format is slightly different depending on your pip tool though, so read the documentation if you don't just use vanilla pip

I used the latest commit and it works.

git+https://github.com/jmrivas86/django-json-widget.git@32c6acf#egg=django-json-widget

What is the difference here? Do you know it?

**Pull request merged**
